### ISSUE TITLE
team.daangn.com: flex-gap 을 margin 으로 대체

### ISSUE THREAD

**Issue by cometkim** [daangn/websites#139]
허허 거참

<img width="898" alt="Screen Shot 2021-06-24 at 6 11 05 PM" src="https://user-images.githubusercontent.com/9696352/124856176-08054500-dfe5-11eb-854e-f79d003cc60f.png">

https://caniuse.com/flexbox-gap

Flexbox의 gap 프로퍼티는 Safari 14.1 부터 지원됩니다. 14도 아니고 14.1 ㅎㅎㅎㅎ

솔직히 저는 아직도 이걸 고쳐야할지 말아야할지 참 고민스럽긴한데... 혹시나 여유 되시는 분은 고쳐주세요. `li + li:before` 나 li:not(first-child)` 같은 셀렉터를 쓰면 될겁니다.

**Comment by stump26** [comment]
캐로셀에서도 gap 동작안해서 폭이 안맞네요
![image](https://user-images.githubusercontent.com/13835452/131705846-d3567427-a9e0-40ab-8ccb-e4090aa974d0.png)

**Comment by cometkim** [comment]
허? 이거 어디서 그래요? 네이버 브라우저는 이러는거 무시했는데 사파리도...? 혹시 버전이 어떤가요

**Comment by cometkim** [comment]
캐러셀은 복잡하게 가는거보다 일반 스크롤 컨테이너로 대체하는게 가장 깔끔할거같아요. 플렉스 스크롤 컨테이너 (+ 옵셔널리 스크롤 스냅)

참고: https://twitter.com/KrComet/status/1420420807294029829?s=19

**Comment by stump26** [comment]
사파리 14.0 이에요

**Comment by cometkim** [comment]
대응 안하기로 결정했습니다. 일단 치명적이지 않습니다. 맥 업데이트하세요
