### ISSUE TITLE
자비로운 종신 독재자의 취향대로 Lint 룰을 통일할 예정

### ISSUE THREAD

**Issue by cometkim** [daangn/websites#49]
- 2 스페이스
- 세미콜론 사용
- Single quote
- 프리티어 안씀 (ESLint or Rome 쓸 예정)

적용 전 이의 제기 받겠습니다.

**Comment by min-uuu** [comment]
여러 의미로 존경합니다 선생님.
언제 한 번 만나뵙고 싶네요.

**Comment by cometkim** [comment]
?? ㅋㅋㅋ @min-uuu 당근마켓 놀러오세요

**Comment by min-uuu** [comment]
@cometkim 사랑합니다 선생님! 꼭 가겠습니다!!

**Comment by beautifulife** [comment]
LGTM!

**Comment by cometkim** [comment]
Rome 사용해서 린트&포매팅 적용했습니다.

https://github.com/daangn/websites/commit/454319ae6dc0c21837a6c7d4e50fd125f1f1a25b
