### ISSUE TITLE
당근마켓 전환체크 중복오류

### ISSUE THREAD

**Issue by 23432rtea1134s** [daangn/websites#992]
안녕하세요.
광고계정이름: 주식회사 더베스트
광고주 도메인: https://xn--2e0bo0vqkf46i.com/
광고추적코드ID: 1694148212689300001

당근마켓 광고를 운영하고 있는데요, 
네이버 및 메타 당근마켓 3가지 광고를 동시에 운영시
네이버 및 메타에서 서비스신청을 해도 당근마켓 카테고리로 잡히고 있습니다.
그래서 어떤 광고가 효율이 좋은지 안좋은지 체크가 안되고 있는 상황인데요.

스크립트는 정상적으로 설치가 된거같은데 
당근마켓으로 서비스신청이 들어온 데이터만 따로 체크하고 싶은데 지금 상태에서 스크립트를 어떻게 수정해야하는지 확인부탁드립니다

**Comment by cometkim** [comment]
안녕하세요. 일단, 답변이 늦어 죄송합니다.
해당 프로젝트는 당근 소유의 컨텐츠 웹사이트만 관리하는 목적으로 운영되고 있어 광고 지원 관련한 사실을 확인해드리기가 어렵습니다.

전환 추적과 관련된 내용은 https://github.com/daangn/karrot-conversion-tracker-tool-support 저장소에 대신 문의 남겨주시면 담당자 분이 안내드릴 수 있을 것 같습니다.

감사합니다.
